// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcdkdwevpgjbhsykblpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjZGtkd2V2cGdqYmhzeWtibHB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MTMwOTksImV4cCI6MjA2NjQ4OTA5OX0.OwpT3OWviBJs1-0IRfYSrcWBrWZRQx8N_sCm29nsm1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);